### PR TITLE
Require Node.js 10

### LINKED ISSUE #1: Support Fish shell
Should add this path `path.join(homeDir, '.config/fish/fish_history')` to the `paths` array, but not sure of the format of the history file. Any Fish users wanna help out?

### PR DESCRIPTION
**Pull request by RocktimSaikia**
- Grouped the test related files.
- Updated the dependencies.
- and few other tweaks

fixes #1 
merging this pr will also fix the style and test issues the person was having with ava and xo in #5 

> Also out of context, while I was updating it I noticed that it was created back in node v4. I was shocked and amazed on how old this repo is. I was still in school at that time :0

// @sindresorhus

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
The tests are passing in local but failing in travis. Weird!

**Comment by RocktimSaikia** [comment]
Ah got it. Since I grouped the test related files into the `test` folder the lib was not able to detect it while testing since it does not exist there so I just changed to current working directory to the test folder when testing with `process.chdir` and now it passed :)

**Comment by sindresorhus** [comment]
I think the upgrade dependencies / project structure should be a separate PR from adding Fish support.

**Comment by sindresorhus** [comment]
I also don't see any special parsing handling for the Fish support.

**Comment by RocktimSaikia** [comment]
@sindresorhus Yes. I thought about it but I personally use `Fish shell` and when I tried logging the command history after adding the fish config paths, it was outputing the history commands just like it should.

**Comment by RocktimSaikia** [comment]
May be I should add some test cases with a fish config file ?

**Comment by RocktimSaikia** [comment]
Updated the PR. Now it's only upgrading the module.
// @sindresorhus

**Pull request merged**
